"""Airtable schema — immutable IDs for the Pear Tracker base.

Generated by scripts/generate_airtable_schema.py at 2026-05-16T01:30:45+00:00.
Do not edit by hand. Add fields to the CURATED dict in that script and re-run.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class UsersTable:
    """Immutable IDs for the Users table."""

    id: str  # tbl…
    email: str  # fld…  — Email
    type: str  # fld…  — Type
    name: str  # fld…  — Name
    phone: str  # fld…  — Phone
    autoreply_agent: str  # fld…  — Autoreply (Agent)
    autoreply_email_agent: str  # fld…  — Autoreply Email (Agent)
    autoreply_enabled_agent: str  # fld…  — Autoreply Enabled (Agent)
    source_record_id: str  # fld…  — Record ID
    autoreply_test_template: str  # fld…  — Autoreply Test Template (Agent)


@dataclass(frozen=True)
class ApartmentsTable:
    """Immutable IDs for the Apartments table."""

    id: str  # tbl…
    streeteasy: str  # fld…  — Streeteasy
    full_address: str  # fld…  — Full Address
    apartment: str  # fld…  — Apartment
    source_record_id: str  # fld…  — Record


@dataclass(frozen=True)
class InquiriesTable:
    """Immutable IDs for the Inquiries table."""

    id: str  # tbl…
    name_form: str  # fld…  — Name (Form)
    email_form: str  # fld…  — Email (Form)
    phone: str  # fld…  — Phone
    message: str  # fld…  — Message
    apartment: str  # fld…  — Apartment
    apartment_failsafe: str  # fld…  — Apartment (FailSafe)
    user: str  # fld…  — User
    method: str  # fld…  — Method
    type_non_website: str  # fld…  — Type (Non Website)
    gmail_message_id_autoreply: str  # fld…  — Gmail Message ID (Autoreply)


@dataclass(frozen=True)
class DraftsTable:
    """Immutable IDs for the Drafts table."""

    id: str  # tbl…
    inquiry: str  # fld…  — Inquiry
    recipient: str  # fld…  — Recipient
    subject: str  # fld…  — Subject
    body_plaintext: str  # fld…  — Body Plaintext
    body_html: str  # fld…  — Body HTML
    source: str  # fld…  — Source
    parser_used: str  # fld…  — Parser Used
    template_source: str  # fld…  — Template Source
    reply_route: str  # fld…  — Reply Route
    skipped_reason: str  # fld…  — Skipped Reason
    apartment_match_strategy: str  # fld…  — Apartment Match Strategy
    apartment_match_confidence: str  # fld…  — Apartment Match Confidence
    llm_model: str  # fld…  — LLM Model
    llm_latency_ms: str  # fld…  — LLM Latency Ms
    would_send_at: str  # fld…  — Would Send At
    notes_warnings: str  # fld…  — Notes / Warnings
    gmail_message_id: str  # fld…  — Gmail Message ID


@dataclass(frozen=True)
class PearTrackerSchema:
    """All curated tables in one Pear Tracker base."""

    base_id: str  # app…
    users: UsersTable
    apartments: ApartmentsTable
    inquiries: InquiriesTable
    drafts: DraftsTable


PROD = PearTrackerSchema(
    base_id="appwPKlnV6YtbIjWz",
    users=UsersTable(
        id="tbl6DvdbIju2MKec6",
        email="fldDCUDfz6AuhILnp",
        type="fldxN6RsgiHNtenGu",
        name="fldmN3zAR0jXLXnfa",
        phone="fld4V6YFX3T6Z3MX4",
        autoreply_agent="fld9F1rE86q7WQ5pb",
        autoreply_email_agent="fldUHK5Kgvp9zjBhD",
        autoreply_enabled_agent="fldmYIlwEtyXvevTT",
        source_record_id="MISSING",  # !! not in this base
        autoreply_test_template="MISSING",  # !! not in this base
    ),
    apartments=ApartmentsTable(
        id="tblSgFofWVoMBCuuk",
        streeteasy="fldDoI2IWTtzkfHvF",
        full_address="fld0uzMqDUC4itTb0",
        apartment="fldPAuiLcx7obyDRA",
        source_record_id="MISSING",  # !! not in this base
    ),
    inquiries=InquiriesTable(
        id="tbl4FU5cnMQVhQB0e",
        name_form="fldkmGXzQnmHVIttE",
        email_form="fldT0fDwpDyoQSv4O",
        phone="fldDwwU02SFzwvP0z",
        message="fldDqEL4pzfoc2WKc",
        apartment="fld4clmwBblEi3tT5",
        apartment_failsafe="fldfghttVslMJmIwJ",
        user="fldiFbSLerxxWyAa8",
        method="fldR8A7B29dPOC4MY",
        type_non_website="fldfS5fKl4WyRQIIQ",
        gmail_message_id_autoreply="fldhH7AoxujABU92O",
    ),
    # WARNING: table 'Drafts' not present in this base
    drafts=DraftsTable(
        id="MISSING",
        inquiry="MISSING",
        recipient="MISSING",
        subject="MISSING",
        body_plaintext="MISSING",
        body_html="MISSING",
        source="MISSING",
        parser_used="MISSING",
        template_source="MISSING",
        reply_route="MISSING",
        skipped_reason="MISSING",
        apartment_match_strategy="MISSING",
        apartment_match_confidence="MISSING",
        llm_model="MISSING",
        llm_latency_ms="MISSING",
        would_send_at="MISSING",
        notes_warnings="MISSING",
        gmail_message_id="MISSING",
    ),
)

TEST = PearTrackerSchema(
    base_id="appmSm1FyerysvtcX",
    users=UsersTable(
        id="tblgCLdJi0BjBAxej",
        email="fldUFXBBKRc5xytxI",
        type="fld9Oo62F2XEIoul5",
        name="flddYErLw7omlqkI0",
        phone="fldsz89gmTzEKtK9r",
        autoreply_agent="fldNfUNc5HY9aRj8I",
        autoreply_email_agent="fld5hNiYESRSr4S3B",
        autoreply_enabled_agent="fldYHuJonBEhzkpjj",
        source_record_id="fld5AATUb99YX3m4C",
        autoreply_test_template="fldnVBEvBY3z8DjBs",
    ),
    apartments=ApartmentsTable(
        id="tblmuWexQ1cT00UPN",
        streeteasy="fldec3u4hqqidusrx",
        full_address="fld2XuvmAdkdvE4d8",
        apartment="fld41e25vAIu7RIqT",
        source_record_id="fldlCZWefoBSSrAZB",
    ),
    inquiries=InquiriesTable(
        id="tbl4FU5cnMQVhQB0e",
        name_form="fldkmGXzQnmHVIttE",
        email_form="fldT0fDwpDyoQSv4O",
        phone="fldDwwU02SFzwvP0z",
        message="fldDqEL4pzfoc2WKc",
        apartment="fld4clmwBblEi3tT5",
        apartment_failsafe="fldfghttVslMJmIwJ",
        user="fldiFbSLerxxWyAa8",
        method="fldR8A7B29dPOC4MY",
        type_non_website="fldfS5fKl4WyRQIIQ",
        gmail_message_id_autoreply="fldhH7AoxujABU92O",
    ),
    drafts=DraftsTable(
        id="tbluW53PER5n6ZyUO",
        inquiry="fldiuL5Osz7B19BUf",
        recipient="fld5FVoKzVYpOsvcd",
        subject="fldeqlVW4ukLsmevz",
        body_plaintext="fld4RWcK9VS7U3V9V",
        body_html="fldGT4EE9Y5Va1Zba",
        source="fldRifdrQv1zTLHe7",
        parser_used="fld4KDDZtBOfyi4as",
        template_source="fldpb4SQM0H37TGDc",
        reply_route="fldgX7yf4HiQUo9ae",
        skipped_reason="fldkGl6UtFtqIs1xu",
        apartment_match_strategy="fldlJ4f21wmXNu1C9",
        apartment_match_confidence="fldEpG3MER845GPZO",
        llm_model="fldlLqQBrGxMcSPKw",
        llm_latency_ms="fldJVtAfriBnk296m",
        would_send_at="fldHxYMp0om865D1g",
        notes_warnings="fldRsySy91rdRGZYW",
        gmail_message_id="fldjiCVfm2qD5r2hs",
    ),
)

SCHEMAS: dict[str, PearTrackerSchema] = {
    PROD.base_id: PROD,
    TEST.base_id: TEST,
}


def get_schema(base_id: str) -> PearTrackerSchema:
    """Resolve the schema for a given Airtable base ID."""
    try:
        return SCHEMAS[base_id]
    except KeyError as exc:
        raise KeyError(f"No schema registered for base {base_id!r}") from exc
