"""Bootstrap helper: dump Airtable bases as a typed schema module.

Reads AIRTABLE_TOKEN, AIRTABLE_BASE_ID, and (optionally) AIRTABLE_STAGING_BASE_ID
from the project `.env`, calls Airtable's metadata API for each, and prints a
ready-to-paste `airtable_schema.py` module with one frozen dataclass per table
plus per-base instances and a SCHEMAS lookup keyed by base ID.

Usage:
    uv run python scripts/dump_airtable_schema.py
    uv run python scripts/dump_airtable_schema.py --out src/autoreplies/services/airtable_schema.py

Re-run any time the base schema changes; diff the output against the committed
module to catch drift.
"""

from __future__ import annotations

import argparse
import datetime as dt
import keyword
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import httpx

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Make `from autoreplies.config import Settings` work regardless of cwd.
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from autoreplies.config import Settings  # noqa: E402

META_URL = "https://api.airtable.com/v0/meta/bases/{base_id}/tables"


# ---------------------------------------------------------------------------
# Identifier sanitization
# ---------------------------------------------------------------------------

_IDENT_NON_ALNUM = re.compile(r"[^0-9a-zA-Z]+")
_IDENT_LEADING_DIGIT = re.compile(r"^(\d)")


def to_py_ident(name: str) -> str:
    """Turn an Airtable display name into a valid snake_case Python identifier."""
    cleaned = _IDENT_NON_ALNUM.sub("_", name).strip("_").lower()
    cleaned = _IDENT_LEADING_DIGIT.sub(r"_\1", cleaned) or "field"
    if keyword.iskeyword(cleaned):
        cleaned += "_"
    return cleaned


def dedupe(names: list[str]) -> list[str]:
    """Append _2, _3, ... to repeated identifiers, preserving order."""
    seen: dict[str, int] = {}
    out: list[str] = []
    for n in names:
        if n in seen:
            seen[n] += 1
            out.append(f"{n}_{seen[n]}")
        else:
            seen[n] = 1
            out.append(n)
    return out


# ---------------------------------------------------------------------------
# Metadata fetch
# ---------------------------------------------------------------------------


@dataclass
class TableMeta:
    id: str
    name: str
    # ordered list of (py_ident, airtable_id, original_name, kind)
    # kind is "field" | "view"
    members: list[tuple[str, str, str, str]] = field(default_factory=list)


def fetch_base(token: str, base_id: str) -> list[TableMeta]:
    """Return one TableMeta per table in the base, with fields + views merged."""
    resp = httpx.get(
        META_URL.format(base_id=base_id),
        headers={"Authorization": f"Bearer {token}"},
        timeout=30.0,
    )
    if resp.status_code == 403:
        raise SystemExit(
            f"403 Forbidden for base {base_id}. The PAT is missing the "
            "'schema.bases:read' scope, or the base isn't in the token's Access list. "
            "Fix at https://airtable.com/create/tokens — no .env change needed."
        )
    if resp.status_code == 404:
        raise SystemExit(f"404 Not Found for base {base_id}. Check the base ID in .env.")
    resp.raise_for_status()
    payload: dict[str, Any] = resp.json()

    tables: list[TableMeta] = []
    for t in payload.get("tables", []):
        raw_idents: list[str] = []
        raw_members: list[tuple[str, str, str]] = []  # (airtable_id, original_name, kind)

        for f in t.get("fields", []):
            raw_idents.append(to_py_ident(f["name"]))
            raw_members.append((f["id"], f["name"], "field"))

        for v in t.get("views", []):
            raw_idents.append(to_py_ident(f"view_{v['name']}"))
            raw_members.append((v["id"], v["name"], "view"))

        deduped = dedupe(raw_idents)
        members = [
            (py, atid, orig, kind)
            for py, (atid, orig, kind) in zip(deduped, raw_members, strict=True)
        ]
        tables.append(TableMeta(id=t["id"], name=t["name"], members=members))

    return tables


# ---------------------------------------------------------------------------
# Code emission
# ---------------------------------------------------------------------------


def emit_module(bases: dict[str, tuple[str, list[TableMeta]]]) -> str:
    """Render the full schema module text.

    `bases` maps a Python constant name (e.g. "PROD") to (base_id, tables).
    """
    timestamp = dt.datetime.now(dt.UTC).isoformat(timespec="seconds")
    lines: list[str] = [
        '"""Airtable schema — immutable IDs for the Pear Tracker base.',
        "",
        f"Generated by scripts/dump_airtable_schema.py at {timestamp}.",
        "Re-run that script and diff if the base schema changes.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
    ]

    # Build one canonical shape per *table name* (union across bases).
    # Each base supplies its own IDs for the same logical attributes.
    canonical: dict[str, list[tuple[str, str, str]]] = {}
    # table_name -> [(py_ident, original_name, kind), ...]
    for _, (_, tables) in bases.items():
        for t in tables:
            existing = canonical.setdefault(t.name, [])
            known_idents = {row[0] for row in existing}
            for py, _atid, orig, kind in t.members:
                if py not in known_idents:
                    existing.append((py, orig, kind))
                    known_idents.add(py)

    # Emit dataclasses (one per table).
    for table_name, members in canonical.items():
        cls = _table_class_name(table_name)
        lines.append("@dataclass(frozen=True)")
        lines.append(f"class {cls}:")
        lines.append('    """Immutable resource IDs for the ' + table_name + ' table."""')
        lines.append("")
        lines.append("    id: str  # tbl…")
        for py, orig, kind in members:
            tag = "fld…" if kind == "field" else "viw…"
            lines.append(f"    {py}: str  # {tag}  — {orig}")
        lines.append("")
        lines.append("")

    # Emit the schema container.
    lines.append("@dataclass(frozen=True)")
    lines.append("class PearTrackerSchema:")
    lines.append('    """All tables in one Pear Tracker base."""')
    lines.append("")
    lines.append("    base_id: str  # app…")
    for table_name in canonical:
        lines.append(f"    {to_py_ident(table_name)}: {_table_class_name(table_name)}")
    lines.append("")
    lines.append("")

    # Emit per-base instances.
    for const_name, (base_id, tables) in bases.items():
        by_name = {t.name: t for t in tables}
        lines.append(f"{const_name} = PearTrackerSchema(")
        lines.append(f'    base_id="{base_id}",')
        for table_name, members in canonical.items():
            attr = to_py_ident(table_name)
            cls = _table_class_name(table_name)
            t = by_name.get(table_name)
            if t is None:
                lines.append(f"    # WARNING: table {table_name!r} not present in this base")
                lines.append(f'    {attr}={cls}(id="MISSING", ' + ", ".join(
                    f'{py}="MISSING"' for py, _, _ in members
                ) + "),")
                continue
            lookup = {orig: atid for _, atid, orig, _ in t.members}
            lines.append(f"    {attr}={cls}(")
            lines.append(f'        id="{t.id}",')
            for py, orig, _kind in members:
                atid = lookup.get(orig, "MISSING")
                marker = "  # !! not in this base" if atid == "MISSING" else ""
                lines.append(f'        {py}="{atid}",{marker}')
            lines.append("    ),")
        lines.append(")")
        lines.append("")

    # Emit lookup.
    lines.append("SCHEMAS: dict[str, PearTrackerSchema] = {")
    for const_name in bases:
        lines.append(f"    {const_name}.base_id: {const_name},")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def get_schema(base_id: str) -> PearTrackerSchema:")
    lines.append('    """Resolve the schema for a given Airtable base ID."""')
    lines.append("    try:")
    lines.append("        return SCHEMAS[base_id]")
    lines.append("    except KeyError as exc:")
    lines.append('        raise KeyError(f"No schema registered for base {base_id!r}") from exc')
    lines.append("")

    return "\n".join(lines)


def _table_class_name(table_name: str) -> str:
    """'Apartments' -> 'ApartmentsTable'; 'Lead Sources' -> 'LeadSourcesTable'."""
    parts = re.split(r"[^0-9a-zA-Z]+", table_name)
    camel = "".join(p[:1].upper() + p[1:] for p in parts if p)
    return f"{camel}Table"


# ---------------------------------------------------------------------------
# Mismatch reporting (stderr)
# ---------------------------------------------------------------------------


def warn_mismatches(bases: dict[str, tuple[str, list[TableMeta]]]) -> None:
    """Print field/table differences between bases to stderr."""
    if len(bases) < 2:
        return
    by_const: dict[str, dict[str, set[str]]] = {}
    for const_name, (_, tables) in bases.items():
        by_const[const_name] = {t.name: {orig for _, _, orig, _ in t.members} for t in tables}

    all_tables = set().union(*(d.keys() for d in by_const.values()))
    for table in sorted(all_tables):
        present_in = {c for c, d in by_const.items() if table in d}
        if present_in != set(by_const):
            missing = set(by_const) - present_in
            print(f"WARN: table {table!r} missing from: {sorted(missing)}", file=sys.stderr)
            continue
        all_fields = set().union(*(by_const[c][table] for c in by_const))
        for c in by_const:
            diff = all_fields - by_const[c][table]
            if diff:
                print(
                    f"WARN: table {table!r} in {c} is missing fields: {sorted(diff)}",
                    file=sys.stderr,
                )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        help="Write generated module here (default: stdout).",
    )
    args = parser.parse_args()

    env_file = PROJECT_ROOT / ".env"
    if not env_file.exists():
        print(f"ERROR: no .env at {env_file}", file=sys.stderr)
        return 2
    settings = Settings(_env_file=str(env_file))  # type: ignore[call-arg]
    if not settings.airtable_token or settings.airtable_token.startswith("pat") and "X" in settings.airtable_token:
        print(
            "ERROR: AIRTABLE_TOKEN not set or still the placeholder. "
            f"Edit {env_file} and replace AIRTABLE_TOKEN with your real PAT.",
            file=sys.stderr,
        )
        return 2

    targets: dict[str, str] = {}
    if settings.airtable_base_id:
        targets["PROD"] = settings.airtable_base_id
    if settings.airtable_staging_base_id:
        targets["STAGING"] = settings.airtable_staging_base_id

    if not targets:
        print("ERROR: no AIRTABLE_BASE_ID or AIRTABLE_STAGING_BASE_ID set", file=sys.stderr)
        return 2

    bases: dict[str, tuple[str, list[TableMeta]]] = {}
    for const_name, base_id in targets.items():
        print(f"Fetching {const_name} base {base_id}…", file=sys.stderr)
        bases[const_name] = (base_id, fetch_base(settings.airtable_token, base_id))

    warn_mismatches(bases)
    out = emit_module(bases)

    if args.out:
        args.out.write_text(out)
        print(f"Wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(out)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
